name: utopia_dart_framework
description: A light and easy to get started with HTTP framework for Dart
version: 0.0.1
homepage: https://github.com/utopia-dart/utopia_dart_framework

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  mime: ^1.0.2
  http_parser: ^4.0.1
  string_scanner: ^1.1.1
  shelf: ^1.3.1
  shelf_static: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
